name: "Built Site Linting"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # dependencies
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - uses: actions/setup-node@v4
        with:
          node-version: '19'
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential zlib1g-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install

      - name: Build the site
        run: bundle exec jekyll build --strict_front_matter

      - name: Validate all links, enforce alt text
        run: |
          gem install html-proofer
          bundle exec htmlproofer \
          --ignore-files "/.*\/ro-crate-preview\.html/" \
          --ignore-urls "/.*pcdm\.org.*/" \
          --disable-external true
          --enforce-https false \
          ./_site

      - name: Ensure no unexpected encoded HTML in output
        run: |
          ! fgrep -R 'lt;blockquote' _site

      - name: Ensure no unexpected jekyll in output
        run: |
          ! fgrep -R 'site.pages' _site
